# Generated by Django 5.2 on 2025-05-19 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.turno'),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('fecha', 'cancha', 'turno')},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='precio_total',
        ),
    ]
